version: '3.8'
services:
  oracle_db1:
    image: container-registry.oracle.com/database/express:latest
    container_name: oracle_db1
    ports:
      - "1521:1521"
    environment:
      ORACLE_PWD: your_password
    restart: always

  oracle_db2:
    image: container-registry.oracle.com/database/express:latest
    container_name: oracle_db2
    ports:
      - "1522:1521"
    environment:
      ORACLE_PWD: your_password
    restart: always